In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\SANTANU SANTRA\Desktop\creditcard.csv')

In [2]:
df.shape

(284807, 31)

In [3]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [2]:
##independent and dependent features
X = df.drop("Class", axis=1)
y = df.Class


In [3]:
#random forest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [5]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3), 'penalty':['l1','l2']}
cv = KFold(n_splits=5,random_state=None, shuffle=False)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7)

In [6]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1, scoring='f1_macro')
clf.fit(X_train, y_train)

C:\Users\SANTANU SANTRA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [7]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85251    40]
 [   47   105]]
0.9989817773252344
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85291
           1       0.72      0.69      0.71       152

    accuracy                           1.00     85443
   macro avg       0.86      0.85      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [9]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85280    11]
 [   31   121]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85291
           1       0.92      0.80      0.85       152

    accuracy                           1.00     85443
   macro avg       0.96      0.90      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [11]:
class_weight=dict({0:1,1:100})

In [12]:
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [13]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85279     6]
 [   39   119]]
0.9994733330992591
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.95      0.75      0.84       158

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# under Sampling

In [10]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns = NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of Classes before fit {}".format(Counter(y_train)))
print("The number of Classes after fit {}".format(Counter(y_train_ns)))

C:\Users\SANTANU SANTRA\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of Classes before fit Counter({0: 199024, 1: 340})
The number of Classes after fit Counter({0: 425, 1: 340})


In [15]:
433*0.8


346.40000000000003

In [11]:

classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [12]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[72792 12499]
 [   10   142]]
0.8535983053029506
              precision    recall  f1-score   support

           0       1.00      0.85      0.92     85291
           1       0.01      0.93      0.02       152

    accuracy                           0.85     85443
   macro avg       0.51      0.89      0.47     85443
weighted avg       1.00      0.85      0.92     85443



In [13]:
#oversampling
from imblearn.over_sampling import RandomOverSampler


In [17]:
os = RandomOverSampler(0.75)
X_train_ns, y_train_ns = os.fit_sample(X_train,y_train)
print("The number of Classes before fit {}".format(Counter(y_train)))
print("The number of Classes after fit {}".format(Counter(y_train_ns)))

C:\Users\SANTANU SANTRA\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of Classes before fit Counter({0: 199024, 1: 340})
The number of Classes after fit Counter({0: 199024, 1: 149268})


In [18]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [19]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85281    10]
 [   31   121]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85291
           1       0.92      0.80      0.86       152

    accuracy                           1.00     85443
   macro avg       0.96      0.90      0.93     85443
weighted avg       1.00      1.00      1.00     85443



# SMOTE Tomek

In [20]:
from imblearn.combine import SMOTETomek

In [24]:
os = SMOTETomek()
X_train_ns, y_train_ns = os.fit_sample(X_train,y_train)
print("The number of Classes before fit {}".format(Counter(y_train)))
print("The number of Classes after fit {}".format(Counter(y_train_ns)))

The number of Classes before fit Counter({0: 199024, 1: 340})
The number of Classes after fit Counter({0: 198419, 1: 198419})


In [25]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [26]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85272    19]
 [   25   127]]
0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85291
           1       0.87      0.84      0.85       152

    accuracy                           1.00     85443
   macro avg       0.93      0.92      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## ensemble technique in imblearn

In [27]:
from imblearn.ensemble import EasyEnsembleClassifier

In [28]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

EasyEnsembleClassifier()

In [29]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82295  2996]
 [   11   141]]
0.9648069473216062
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85291
           1       0.04      0.93      0.09       152

    accuracy                           0.96     85443
   macro avg       0.52      0.95      0.53     85443
weighted avg       1.00      0.96      0.98     85443

